In [0]:
#Importing Libraries, Implementing Kernel SVM with Scikit-Learn
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
# Importing the Dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

In [0]:
# Preprocessing
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']

In [162]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
print (X_train)

     sepal-length  sepal-width  petal-length  petal-width
125           7.2          3.2           6.0          1.8
77            6.7          3.0           5.0          1.7
9             4.9          3.1           1.5          0.1
69            5.6          2.5           3.9          1.1
1             4.9          3.0           1.4          0.2
..            ...          ...           ...          ...
89            5.5          2.5           4.0          1.3
137           6.4          3.1           5.5          1.8
37            4.9          3.1           1.5          0.1
46            5.1          3.8           1.6          0.2
47            4.6          3.2           1.4          0.2

[120 rows x 4 columns]


In [163]:
# Training the Algorithm
# To train the kernel SVM, we use the same SVC class of the Scikit-Learn's svm library. The difference lies in the value for the kernel parameter of the SVC class.
#  for kernel SVM you can use Gaussian, polynomial, sigmoid, or computable kernel.
from sklearn.svm import SVC
#svclassifier = SVC(kernel='poly', degree=10)
#svclassifier = SVC(kernel='sigmoid')
svclassifier = SVC(kernel='rbf', gamma=1/4)
#svclassifier = SVC(kernel='linear')

svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.25, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [164]:
# Making Predictions & evaluation
y_pred = svclassifier.predict(X_test)

# Evaluating the Algorithm

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 7  0  0]
 [ 0  9  0]
 [ 0  0 14]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        14

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

